### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by hazel-web** [haskell-hvr/http-io-streams#1]
cabal install http-io-streams   
resolving dependencies...    
Build profile: -w ghc-8.10.2 -O1 
cabal.exe: Failed to build brotli-0.0.0.0 
'pkg-config' version >=0.9.0 is required but it could not be found.

**Comment by andreasabel** [comment]
@hazel-web : You need `pkg-config` on your system and also the `brotli` library.
Maybe you can extract some information about the setup from: https://github.com/hackage-trustees/hackage-cli/blob/87e79c0867f9bcf0b75524a26b34bb87dad1dd69/.github/workflows/stack.yml

Reopen issue if necessary.
