### ISSUE TITLE
request to replace deprecated `system-fileio` with `directory`

### ISSUE THREAD

**Issue by peterbecich** [haskell-hvr/http-io-streams#17]
Hello, I am attempting to build `http-io-streams` with Nix. Specifically, `hackage-server` depends on `http-io-streams`, and I'm attempting to update the Nix build of `hackage-server`: https://github.com/haskell/hackage-server/pull/1283

I am having difficulty with `http-io-stream`'s dependency on deprecated package https://hackage.haskell.org/package/system-fileio

Can this be replaced with https://hackage.haskell.org/package/directory ?

Thank you

**Comment by andreasabel** [comment]
> [system-fileio](https://hackage.haskell.org/package/system-fileio)
> 
> Can this be replaced with [hackage.haskell.org/package/directory](https://hackage.haskell.org/package/directory) ?

Well, yes it can, but someone has to do it, and there is a risk of regressions, like it happened for `shelly`:
- https://github.com/gregwebs/Shelly.hs/pull/182
- https://github.com/gregwebs/Shelly.hs/issues/189
